-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.alembic_version (
  version_num character varying NOT NULL,
  CONSTRAINT alembic_version_pkey PRIMARY KEY (version_num)
);
CREATE TABLE public.ingestion_runs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  status text NOT NULL CHECK (status = ANY (ARRAY['running'::text, 'completed'::text, 'completed_with_warnings'::text, 'failed'::text])),
  triggered_by text,
  source_file_count integer NOT NULL DEFAULT 0,
  total_rows_seen integer NOT NULL DEFAULT 0,
  total_rows_loaded integer NOT NULL DEFAULT 0,
  total_rows_skipped integer NOT NULL DEFAULT 0,
  warning_count integer NOT NULL DEFAULT 0,
  error_count integer NOT NULL DEFAULT 0,
  summary_json json,
  CONSTRAINT ingestion_runs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.source_files (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  original_filename text NOT NULL,
  file_hash text NOT NULL UNIQUE,
  file_type text NOT NULL,
  source_type text NOT NULL,
  country_scope text,
  period_start date,
  period_end date,
  detected_sheet_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT source_files_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ingestion_run_files (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  ingestion_run_id uuid NOT NULL,
  source_file_id uuid NOT NULL,
  local_path_snapshot text,
  status text NOT NULL,
  sheets_profiled integer NOT NULL DEFAULT 0,
  rows_seen integer NOT NULL DEFAULT 0,
  rows_loaded integer NOT NULL DEFAULT 0,
  rows_skipped integer NOT NULL DEFAULT 0,
  warnings integer NOT NULL DEFAULT 0,
  errors integer NOT NULL DEFAULT 0,
  profile_json json,
  CONSTRAINT ingestion_run_files_pkey PRIMARY KEY (id),
  CONSTRAINT ingestion_run_files_ingestion_run_id_fkey FOREIGN KEY (ingestion_run_id) REFERENCES public.ingestion_runs(id),
  CONSTRAINT ingestion_run_files_source_file_id_fkey FOREIGN KEY (source_file_id) REFERENCES public.source_files(id)
);
CREATE TABLE public.validation_errors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  ingestion_run_id uuid NOT NULL,
  source_file_id uuid,
  sheet_name text,
  row_number integer,
  severity text NOT NULL CHECK (severity = ANY (ARRAY['info'::text, 'warning'::text, 'error'::text])),
  entity_type text,
  field_name text,
  error_code text NOT NULL,
  message text NOT NULL,
  raw_value text,
  CONSTRAINT validation_errors_pkey PRIMARY KEY (id),
  CONSTRAINT validation_errors_ingestion_run_id_fkey FOREIGN KEY (ingestion_run_id) REFERENCES public.ingestion_runs(id),
  CONSTRAINT validation_errors_source_file_id_fkey FOREIGN KEY (source_file_id) REFERENCES public.source_files(id)
);
CREATE TABLE public.countries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  code text NOT NULL UNIQUE,
  default_currency_code text NOT NULL,
  CONSTRAINT countries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.calendar_months (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  month_start_date date NOT NULL UNIQUE,
  month_label text NOT NULL,
  fiscal_year text NOT NULL,
  fiscal_month_number integer NOT NULL,
  calendar_year integer NOT NULL,
  calendar_month_number integer NOT NULL,
  CONSTRAINT calendar_months_pkey PRIMARY KEY (id)
);
CREATE TABLE public.exchange_rates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  currency_code text NOT NULL,
  rate_to_usd numeric,
  rate_date date,
  source text NOT NULL,
  rate_status text NOT NULL CHECK (rate_status = ANY (ARRAY['official'::text, 'provisional'::text, 'missing'::text])),
  CONSTRAINT exchange_rates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.plan_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  source_file_id uuid NOT NULL,
  ingestion_run_id uuid NOT NULL,
  country_id uuid NOT NULL,
  calendar_month_id uuid NOT NULL,
  fiscal_year text,
  therapy text,
  event_type text,
  event_name text NOT NULL,
  event_name_normalized text NOT NULL,
  central_or_local text,
  brand_name_1 text,
  brand_name_2 text,
  planned_total_hcps integer,
  planned_patients integer,
  planned_pharmacies integer,
  total_planned_cost_usd numeric,
  source_sheet_name text NOT NULL,
  source_row_number integer NOT NULL,
  CONSTRAINT plan_events_pkey PRIMARY KEY (id),
  CONSTRAINT plan_events_source_file_id_fkey FOREIGN KEY (source_file_id) REFERENCES public.source_files(id),
  CONSTRAINT plan_events_ingestion_run_id_fkey FOREIGN KEY (ingestion_run_id) REFERENCES public.ingestion_runs(id),
  CONSTRAINT plan_events_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id),
  CONSTRAINT plan_events_calendar_month_id_fkey FOREIGN KEY (calendar_month_id) REFERENCES public.calendar_months(id)
);
CREATE TABLE public.execution_snapshots (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  source_file_id uuid NOT NULL,
  ingestion_run_id uuid NOT NULL,
  country_id uuid NOT NULL,
  calendar_month_id uuid NOT NULL,
  therapy text,
  event_type text,
  event_name text NOT NULL,
  event_name_normalized text NOT NULL,
  planned_hcps integer,
  engaged_hcps integer,
  raised_request_count integer,
  snapshot_source text NOT NULL,
  status_source_value text,
  normalized_status text NOT NULL,
  source_sheet_name text NOT NULL,
  source_row_number integer NOT NULL,
  CONSTRAINT execution_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT execution_snapshots_source_file_id_fkey FOREIGN KEY (source_file_id) REFERENCES public.source_files(id),
  CONSTRAINT execution_snapshots_ingestion_run_id_fkey FOREIGN KEY (ingestion_run_id) REFERENCES public.ingestion_runs(id),
  CONSTRAINT execution_snapshots_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id),
  CONSTRAINT execution_snapshots_calendar_month_id_fkey FOREIGN KEY (calendar_month_id) REFERENCES public.calendar_months(id)
);
CREATE TABLE public.execution_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  source_file_id uuid NOT NULL,
  ingestion_run_id uuid NOT NULL,
  source_system text NOT NULL DEFAULT 'consolidation'::text,
  req_id text,
  request_uid text NOT NULL UNIQUE,
  country_id uuid NOT NULL,
  calendar_month_id uuid NOT NULL,
  rep_code text,
  rep_name text,
  intervention_date date,
  actual_intervention_date date,
  venue text,
  intervention_name text NOT NULL,
  intervention_name_normalized text NOT NULL,
  intervention_type text,
  intervention_sub_type text,
  estimated_intervention_local numeric,
  confirmed_contracted_amount_local numeric,
  confirmed_vs_estimated_variance_local numeric,
  actual_total_expense_local numeric,
  actual_btu_expense_local numeric,
  actual_btc_expense_local numeric,
  association_amount_local numeric,
  currency_code text NOT NULL,
  fx_rate_to_usd numeric,
  fx_rate_status text NOT NULL,
  request_approval_status text,
  request_confirmation_status text,
  post_approval_status text,
  post_confirmation_status text,
  current_owner_stage text,
  approval_chain_json json,
  source_row_number integer NOT NULL,
  CONSTRAINT execution_requests_pkey PRIMARY KEY (id),
  CONSTRAINT execution_requests_source_file_id_fkey FOREIGN KEY (source_file_id) REFERENCES public.source_files(id),
  CONSTRAINT execution_requests_ingestion_run_id_fkey FOREIGN KEY (ingestion_run_id) REFERENCES public.ingestion_runs(id),
  CONSTRAINT execution_requests_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id),
  CONSTRAINT execution_requests_calendar_month_id_fkey FOREIGN KEY (calendar_month_id) REFERENCES public.calendar_months(id)
);
CREATE TABLE public.request_doctors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  execution_request_id uuid NOT NULL,
  attendance_type text NOT NULL,
  doctor_name_raw text,
  doctor_class_raw text,
  pcode_raw text,
  pcode_normalized text,
  parse_status text NOT NULL,
  source_position integer NOT NULL,
  CONSTRAINT request_doctors_pkey PRIMARY KEY (id),
  CONSTRAINT request_doctors_execution_request_id_fkey FOREIGN KEY (execution_request_id) REFERENCES public.execution_requests(id)
);
CREATE TABLE public.doctors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  country_id uuid NOT NULL,
  pcode_normalized text NOT NULL,
  latest_doctor_name text,
  speciality text,
  doctor_class text,
  patch_name text,
  active_status text,
  source_count integer NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT doctors_pkey PRIMARY KEY (id),
  CONSTRAINT doctors_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id)
);
CREATE TABLE public.rcpa_prescriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  source_file_id uuid NOT NULL,
  ingestion_run_id uuid NOT NULL,
  country_id uuid NOT NULL,
  calendar_month_id uuid NOT NULL,
  pcode_raw text,
  pcode_normalized text NOT NULL,
  doctor_name text,
  brand_group text NOT NULL,
  sku text NOT NULL,
  own_or_competitor text NOT NULL,
  prescription_qty numeric NOT NULL,
  prescription_value_local numeric,
  currency_code text NOT NULL,
  prescription_value_usd numeric,
  row_count_aggregated integer NOT NULL,
  CONSTRAINT rcpa_prescriptions_pkey PRIMARY KEY (id),
  CONSTRAINT rcpa_prescriptions_source_file_id_fkey FOREIGN KEY (source_file_id) REFERENCES public.source_files(id),
  CONSTRAINT rcpa_prescriptions_ingestion_run_id_fkey FOREIGN KEY (ingestion_run_id) REFERENCES public.ingestion_runs(id),
  CONSTRAINT rcpa_prescriptions_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id),
  CONSTRAINT rcpa_prescriptions_calendar_month_id_fkey FOREIGN KEY (calendar_month_id) REFERENCES public.calendar_months(id)
);
CREATE TABLE public.event_matches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  ingestion_run_id uuid NOT NULL,
  country_id uuid NOT NULL,
  calendar_month_id uuid NOT NULL,
  plan_event_id uuid,
  execution_snapshot_id uuid,
  execution_request_id uuid,
  match_method text NOT NULL,
  match_confidence numeric NOT NULL,
  match_status text NOT NULL,
  matched_on json,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT event_matches_pkey PRIMARY KEY (id),
  CONSTRAINT event_matches_ingestion_run_id_fkey FOREIGN KEY (ingestion_run_id) REFERENCES public.ingestion_runs(id),
  CONSTRAINT event_matches_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id),
  CONSTRAINT event_matches_calendar_month_id_fkey FOREIGN KEY (calendar_month_id) REFERENCES public.calendar_months(id),
  CONSTRAINT event_matches_plan_event_id_fkey FOREIGN KEY (plan_event_id) REFERENCES public.plan_events(id),
  CONSTRAINT event_matches_execution_snapshot_id_fkey FOREIGN KEY (execution_snapshot_id) REFERENCES public.execution_snapshots(id),
  CONSTRAINT event_matches_execution_request_id_fkey FOREIGN KEY (execution_request_id) REFERENCES public.execution_requests(id)
);
CREATE TABLE public.ai_query_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  country_id uuid,
  calendar_month_id uuid,
  question_redacted text NOT NULL,
  context_summary_json json NOT NULL,
  answer text,
  provider text NOT NULL,
  model text,
  latency_ms integer,
  error_code text,
  error_message text,
  CONSTRAINT ai_query_logs_pkey PRIMARY KEY (id),
  CONSTRAINT ai_query_logs_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id),
  CONSTRAINT ai_query_logs_calendar_month_id_fkey FOREIGN KEY (calendar_month_id) REFERENCES public.calendar_months(id)
);